version: "3"
services:

  qe-test-base:
    image: prismagraphql/build:test
    environment:
      SERVER_ROOT: /root/build
      COMMIT_SHA: "ci_test_binary"
      RUST_BACKTRACE: "1"
      IS_BUILDKITE: "1"
      RUST_LOG_FORMAT: "devel"
      LOG_LEVEL: "error"
    volumes:
      - .:/root/build
    working_dir: /root/build/
    networks:
      - databases

  test-db-postgres-13:
    image: cockroachdb/cockroach:latest
    restart: always
    command: start --insecure -s /cockroachfs20 
    networks:
      - databases
    ports:
      - "5435:26257" # Database
      - "8036:8080" # Web UI
    tmpfs: /cockroachfs20


networks:
  databases:
