name: Introspection Engine
on:
  push:

jobs:

  test:
    name: "Test Introspection Engine - postgres13"
        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: docker-compose up -d
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.48.0
          default: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: introspection-engine-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: cargo test postgres13
        working-directory: introspection-engine/introspection-engine-tests
        env:
          CLICOLOR_FORCE: 1
          
      - run: docker ps -a
        if: ${{ always() }}
      - run: docker logs prisma-engines_test-db-postgres-13_1
        if: ${{ always() }}
